### PR TITLE
Fix environment variable values from escaping

### PR DESCRIPTION
**Pull request by knipknap**
This fixes an escaping issue

### CODE REVIEW

**Comment by AngelOnFira** [comment]
Hey @knipknap, thanks for the PR! Just want to understand a bit more about the issue. I assume this is referring to environment keys that might have bash commands, or other evaluatable symbols in the value? I can't particularly think of any that would be important for an env file, but maybe my workflow doesn't run into what yours might.

On the other hand, it is common to have quotes around values of envfiles, so that might be useful? But I'd still be interested to hear more about what the "escaping issue" entails.

**Comment by knipknap** [comment]
Phew, honestly, I don't quite remember what the problem was. I had generated passwords with all kinds of special chars in them, and tried to put them into the .env file. I think it was related to backslashes, which due to being passed around more than once made handling impossible. The only way I could figure out how to fix it was by using single quotes in the action.

I just retested and indeed, using your version fails, even if I use single quotes like this:

```
envkey_DOMAIN: '${{ secrets.DOMAIN }}'
```

If there's a reliable way to pass strings with backslashes into the file, I didn't find it.

**Comment by knipknap** [comment]
Oh, wait... it failed for another reason. Sorry about that. The problem is actually something else. In other words, please disregard this pull request.

**Comment by AngelOnFira** [comment]
No worries, this still did open up a can of worms that I hadn't considered. I'm going to look into this further, as it might be useful to at least add some tests for anyone to be able to reference instead of having to read the source and make sure it doesn't miss any edge cases.

**Pull request closed without merging**
